package net.darkhax.moreswords;

import java.util.Arrays;

import net.darkhax.moreswords.enchantment.Enchantments;
import net.darkhax.moreswords.handler.ConfigurationHandler;
import net.darkhax.moreswords.handler.MobHandler;
import net.darkhax.moreswords.handler.RecipeHandler;
import net.darkhax.moreswords.item.SwordItems;
import net.darkhax.moreswords.plugins.Plugin;
import net.darkhax.moreswords.proxy.CommonProxy;
import net.darkhax.moreswords.util.Constants;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.VERSION_NUMBER, guiFactory = Constants.FACTORY)
public class MoreSwords {

    @SidedProxy(clientSide = Constants.CLIENT_PROXY_CLASS, serverSide = Constants.SERVER_PROXY_CLASS)
    public static CommonProxy proxy;

    @Mod.Instance(Constants.MOD_ID)
    public static MoreSwords instance;

    @EventHandler
    public void preInit(FMLPreInitializationEvent pre) {

        setModInfo(pre.getModMetadata());
        proxy.registerSidedEvents();
        new ConfigurationHandler(pre.getSuggestedConfigurationFile());
        new SwordItems();
        new Enchantments(ConfigurationHandler.enabledEnchant);
        new RecipeHandler(ConfigurationHandler.itemsCraftable);
        new MobHandler(ConfigurationHandler.enabledSpawning);
    }

    @EventHandler
    public void init(FMLInitializationEvent init) {

        proxy.registerRenders();
        new Plugin(ConfigurationHandler.enabledPlugins);
    }

    /**
     * Allows for mod information to be supplied through code rather than an mcmod.info file.
     * 
     * @param meta: The ModMetadata for the mod instance.
     */
    void setModInfo(ModMetadata meta) {

        meta.authorList = Arrays.asList("Darkhax");
        meta.logoFile = "";
        meta.credits = "Maintained by Darkhax";
        meta.description = "More Swords provides a magnificent chain of lustrous new swords that expound upon the foundation of Minecraft weaponry. Razor sharp swords of magic as well as stronger, more practical blaes!";
        meta.url = "http://darkhax.net";
        meta.autogenerated = false;
    }
}